CREATE DATABASE budgio_db;

\c budgio_db;

CREATE TABLE "User" (
    "Id" VARCHAR(64) PRIMARY KEY,
    "Name" VARCHAR(128) NOT NULL,
    "Email" VARCHAR(128) NOT NULL,
    "PasswordHash" TEXT,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE "Expense" (
    "Id" VARCHAR(64) PRIMARY KEY,
    "InstallmentAmount" NUMERIC NOT NULL,
    "Name" VARCHAR(64) NOT NULL,
    "DueDate" DATE NOT NULL,
    "UserId" VARCHAR(64) NOT NULL REFERENCES "User"("Id"),
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE,
    "Paid" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE "CheckingAccount" (
    "Id" VARCHAR(64) PRIMARY KEY,
    "Name" VARCHAR(64) NOT NULL,
    "Balance" NUMERIC NOT NULL,
    "Color" VARCHAR(6) NOT NULL DEFAULT '007a33',
    "UserId" VARCHAR(64) NOT NULL REFERENCES "User"("Id"),
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE "HistoryCheckingAccount" (
    "Id" VARCHAR(64) PRIMARY KEY,
    "CheckingAccountId" VARCHAR(64) NOT NULL,
    "Balance" NUMERIC NOT NULL,
    "Date" TIMESTAMP NOT NULL,
    "Description" TEXT,
    FOREIGN KEY ("CheckingAccountId") REFERENCES "CheckingAccount"("Id")
);


CREATE TABLE "CreditCard" (
    "Id" VARCHAR(64) PRIMARY KEY,
    "CreditLimit" NUMERIC NOT NULL,
    "Name" VARCHAR(64) NOT NULL,
    "Color" VARCHAR(6) NOT NULL DEFAULT '007A33',
    "DueDate" DATE NOT NULL,
    "UserId" VARCHAR(64) NOT NULL REFERENCES "User"("Id"),
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE
);

CREATE TABLE "ExpenseCreditCard" (
    "Id" VARCHAR(64) PRIMARY KEY,
    "CreditCardId" VARCHAR(64) NOT NULL REFERENCES "CreditCard"("Id"),
    "Name" VARCHAR(64) NOT NULL,
    "IssueDate" DATE NOT NULL,
    "TotalInstallments" INTEGER NOT NULL,
    "InstallmentAmount" NUMERIC NOT NULL,
    "TotalCost" NUMERIC NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE
);